# Generated by Django 6.0.1 on 2026-01-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(db_comment='унікальний код', primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='повна назва', max_length=255, verbose_name='Назва кафедри')),
                ('short_name', models.CharField(blank=True, db_comment='абревіатура', max_length=50, null=True, verbose_name='Абревіатура')),
                ('mail', models.CharField(blank=True, db_comment='пошта кафедри/відділу', max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Підрозділ',
                'verbose_name_plural': 'Підрозділи',
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id_position', models.AutoField(db_comment='унікальний код', primary_key=True, serialize=False)),
                ('title', models.CharField(db_comment='назва посади', max_length=100, verbose_name='Назва посади')),
            ],
            options={
                'verbose_name': 'Посада',
                'verbose_name_plural': 'Посади',
                'db_table': 'position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TypeDepartment',
            fields=[
                ('id_type_department', models.AutoField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(max_length=45, verbose_name='Тип підрозділу')),
            ],
            options={
                'verbose_name': 'Тип підрозділу',
                'verbose_name_plural': 'Типи підрозділів',
                'db_table': 'type_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(db_comment='код співробітника', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_comment='ПІБ', max_length=150, verbose_name='ПІБ')),
                ('phone_number', models.CharField(blank=True, db_comment='номер телефону', max_length=20, null=True, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, db_comment='особиста пошта', max_length=100, null=True, verbose_name='Email')),
                ('office', models.CharField(blank=True, db_comment='кабінет / аудиторія', max_length=20, null=True, verbose_name='Кабінет')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='Підрозділ')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position', verbose_name='Посада')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='type_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.typedepartment', verbose_name='Тип'),
        ),
    ]
