# Generated by Django 6.0.1 on 2026-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mail',
            field=models.CharField(blank=True, db_comment='пошта кафедри/відділу', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, db_comment='абревіатура', max_length=50, null=True),
        ),
    ]
