# Generated by Django 6.0.1 on 2026-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='show_in_structure',
            field=models.BooleanField(default=True, verbose_name='показувати в структурі'),
        ),
    ]
