# Generated by Django 6.0.1 on 2026-01-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_department_mail_alter_department_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_comment='повна назва', max_length=255, verbose_name='Назва кафедри'),
        ),
        migrations.AlterField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Абревіатура'),
        ),
        migrations.AlterField(
            model_name='department',
            name='type_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.typedepartment', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='Підрозділ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кабінет'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.position', verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва посади'),
        ),
        migrations.AlterField(
            model_name='typedepartment',
            name='name_type',
            field=models.CharField(max_length=45, verbose_name='Тип підрозділу'),
        ),
    ]
