# Generated by Django 6.0.1 on 2026-03-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_department_show_in_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees_photos/', verbose_name='Фотографія'),
        ),
    ]
